# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jihoon Park"
resume_title:                   "Ph.D Student @ SNU, South Korea"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jihoonpark@snu.ac.kr"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+82.I0.2709.78I8"
resume_contact_address:         "VLSI Lab., Seoul National University, Seoul, South Korea"

resume_header_contact_info:     "VLSI Lab., Seoul National University, Seoul, South Korea • +82.I0.2709.78I8 • jihoonpark@snu.ac.kr"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a full-time student at Seoul National University, pursuing a Ph.D degree in the electrical and computer engineering. My current research interests include efficient deep learning algorithm/hardware and in-memory computing hardware at a system & application-level perspective. I'm also an amateur vim, linux enthusiast. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "http://twitter.com/jglovier"
  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
